### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by SFJake** [ryan-cranfill/hl-paker#2]
Traceback (most recent call last):
  File "wizard_gui.py", line 125, in <module>
  File "wizard_gui.py", line 54, in main
  File "adb_util.py", line 28, in find_quest_devices
  File "ppadb\command\transport\__init__.py", line 94, in get_properties
  File "ppadb\command\transport\__init__.py", line 20, in shell
  File "ppadb\device.py", line 45, in create_connection
  File "ppadb\command\transport\__init__.py", line 15, in transport
  File "ppadb\connection.py", line 84, in send
  File "ppadb\connection.py", line 90, in _check_status
RuntimeError: ERROR: 'FAIL' 000edevice offline

That is all.

**Comment by SFJake** [comment]
I simply needed the ADB drivers installed.

**Comment by ryan-cranfill** [comment]
Ah, thanks for letting me know you were able to resolve!
